--- 
- :uri: http://www.r4isstatic.com/linkeddata/ontologies/ontomedia/core/expression.owl
  :format: rdfxml
  :namespace: ome
- :uri: http://www.r4isstatic.com/linkeddata/ontologies/ontomedia/core/media.owl
  :format: rdfxml
  :namespace: media  
- :uri: http://www.r4isstatic.com/linkeddata/ontologies/ontomedia/core/space.owl
  :format: rdfxml
  :namespace: sp
- :uri: http://www.r4isstatic.com/linkeddata/ontologies/ontomedia/misc/AKTlocation.owl
  :format: rdfxml
  :namespace: aktloc
- :uri: http://www.r4isstatic.com/linkeddata/ontologies/ontomedia/misc/colour.owl
  :format: rdfxml
- :uri: http://www.r4isstatic.com/linkeddata/ontologies/ontomedia/misc/date.owl
  :format: rdfxml
- :uri: http://www.r4isstatic.com/linkeddata/ontologies/ontomedia/misc/geometry.owl
  :format: rdfxml
  :namespace: geom
- :uri: http://www.r4isstatic.com/linkeddata/ontologies/ontomedia/misc/location.owl
  :format: rdfxml
- :uri: http://www.r4isstatic.com/linkeddata/ontologies/ontomedia/misc/locspec.owl
  :format: rdfxml
  :namespace: locspec
- :uri: http://www.r4isstatic.com/linkeddata/ontologies/ontomedia/misc/name.owl
  :format: rdfxml
- :uri: http://www.r4isstatic.com/linkeddata/ontologies/ontomedia/ext/common/being.owl
  :format: rdfxml
- :uri: http://www.r4isstatic.com/linkeddata/ontologies/ontomedia/ext/common/bestiary.owl
  :format: rdfxml
- :uri: http://www.r4isstatic.com/linkeddata/ontologies/ontomedia/ext/common/exprop.owl
  :format: rdfxml
- :uri: http://www.r4isstatic.com/linkeddata/ontologies/ontomedia/ext/common/physical_items.owl
  :format: rdfxml
- :uri: http://www.r4isstatic.com/linkeddata/ontologies/ontomedia/ext/common/profession.owl
  :format: rdfxml
- :uri: http://www.r4isstatic.com/linkeddata/ontologies/ontomedia/ext/common/trait.owl
  :format: rdfxml
- :uri: http://www.r4isstatic.com/linkeddata/ontologies/ontomedia/ext/common/zoology.owl
  :format: rdfxml
- :uri: http://www.r4isstatic.com/linkeddata/ontologies/ontomedia/ext/details/jobs.owl
  :format: rdfxml
- :uri: http://www.r4isstatic.com/linkeddata/ontologies/ontomedia/ext/details/know.owl
  :format: rdfxml
- :uri: http://www.r4isstatic.com/linkeddata/ontologies/ontomedia/ext/details/jobs.owl
  :format: rdfxml
- :uri: http://www.r4isstatic.com/linkeddata/whoniverse/
  :format: rdfxml
  :namespace: whoniverse
